import type {DonationToken} from '../types/web3'

export const DONATION_RECEIVER =
    import.meta.env.VITE_DONATION_EVM_RECEIVER || '0x718a544638Fd113A58C1062E4b2E8a404b13D2eC'

export const SUPPORTED_DONATION_TOKENS = [
    {
        id: 'eth-native',
        chainId: 1n,
        chainHex: '0x1',
        networkName: 'Ethereum',
        symbol: 'ETH',
        type: 'native',
        decimals: 18,
        explorer: 'https://etherscan.io/',
    },
    {
        id: 'eth-usdc',
        chainId: 1n,
        chainHex: '0x1',
        networkName: 'Ethereum',
        symbol: 'USDC',
        type: 'erc20',
        decimals: 6,
        contract: '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48',
        explorer: 'https://etherscan.io/',
    },
    {
        id: 'polygon-native',
        chainId: 137n,
        chainHex: '0x89',
        networkName: 'Polygon',
        symbol: 'POL',
        type: 'native',
        decimals: 18,
        explorer: 'https://polygonscan.com/',
    },
    {
        id: 'polygon-usdc',
        chainId: 137n,
        chainHex: '0x89',
        networkName: 'Polygon',
        symbol: 'USDC',
        type: 'erc20',
        decimals: 6,
        contract: '0x3c499c542cef5e3811e1192ce70d8cc03d5c3359',
        explorer: 'https://polygonscan.com/',
    },
    {
        id: 'arbitrum-native',
        chainId: 42161n,
        chainHex: '0xa4b1',
        networkName: 'Arbitrum',
        symbol: 'ETH',
        type: 'native',
        decimals: 18,
        explorer: 'https://arbiscan.io/',
    },
    {
        id: 'arbitrum-usdc',
        chainId: 42161n,
        chainHex: '0xa4b1',
        networkName: 'Arbitrum',
        symbol: 'USDC',
        type: 'erc20',
        decimals: 6,
        contract: '0xaf88d065e77c8cC2239327C5EDb3A432268e5831',
        explorer: 'https://arbiscan.io/',
    },
    {
        id: 'bnb-native',
        chainId: 56n,
        chainHex: '0x38',
        networkName: 'BNB Chain',
        symbol: 'BNB',
        type: 'native',
        decimals: 18,
        explorer: 'https://bscscan.com/',
    },
    {
        id: 'bnb-usdc',
        chainId: 56n,
        chainHex: '0x38',
        networkName: 'BNB Chain',
        symbol: 'USDC',
        type: 'erc20',
        decimals: 18,
        contract: '0x8ac76a51cc950d9822d68b83fe1ad97b32cd580d',
        explorer: 'https://bscscan.com/',
    },
] as const satisfies readonly DonationToken[]
